condense_wildcard_suffixes = true
fn_single_line = true
imports_layout = "HorizontalVertical"
max_width = 80
merge_imports = true
normalize_comments = true
reorder_impl_items = true
wrap_comments = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
